
spring:
  datasource:
    url: jdbc:h2:mem:testd
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
        enabled: true
        path: /h2

  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    java.net.*: ERROR
    com.sun.*: ERROR
    org.springframework.security.web.*: ERROR
    org.springframework.web: ERROR
    org.hibernate: DEBUG
    root: INFO
    api.*:
